name: Pyinstaller Build Test
run-name: ${{ github.actor }} is building python code.
on: 
  push:
  workflow_dispatch:

jobs:

  stage:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, 'TRG_BUILD')
    steps:
    - name: Stage the python source.
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: 'pip' # caching pip dependencies
    - run: pip install -r staged/stage-requirements.txt
    - run: python staged/stager.py

    - uses: actions/upload-artifact@master
      with:
        name: fused
        path: staged/fused/__init__.py

  linux:
    needs: stage
    runs-on: ubuntu-latest
    steps:
    - name: Build with pyinstaller, targeting linux_x86_64.
      uses: actions/checkout@v4

    - uses: actions/download-artifact@master
      with:
        name: fused
        path: staged/fused

    - uses: sayyid5416/pyinstaller@v1
      with:
        python_ver: '3.12'
        pyinstaller_ver: '==6.10.0'
        spec: 'staged/fused/__init__.py'
        requirements: 'src/requirements.txt'
        clean_checkout: false
        exe_path: "./builds"
        options: --onefile, --name "ExampleApp"

    - uses: actions/upload-artifact@master
      with:
        name: linux_x86_64
        path: builds/*
