name: Pyinstaller Build Test
run-name: ${{ github.actor }} is building python code.
on: [push]
jobs:

  stage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: 'pip' # caching pip dependencies
    - run: pip install -r stage-requirements.txt
    - run: python staged/stage.py

    - uses: actions/upload-artifact@master
      with:
        name: fused
        path: staged/fused/staged.py

  linux:
    needs: stage
    runs-on: ubuntu-latest
    steps:
        
    - uses: actions/checkout@v4

    - uses: actions/download-artifact@master
      with:
        name: fused
        path: staged/fused/staged.py

    - run: ls staged/fused/

    - run: cat staged/fused/staged.py
