name: Python Build Test-Workflow
run-name: ${{ github.actor }} is building python code.
on: [push]
jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version-file: pyproject.toml
        #cache: 'pip' # caching pip dependencies
    - run: pip install -r requirements.txt
    - run: python example.py