name: Pyinstaller Test
run-name: ${{ github.actor }} is testing python code.
on:
  workflow_dispatch:

jobs:

  stage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: 'pip' # caching pip dependencies
        
    - run: pip install -r staged/stager_requirements.txt
    - run: python staged/stager.py

    - uses: actions/upload-artifact@master
      with:
        name: fused
        path: staged/o/fused/*

    - run: pip install -r src/requirements.txt
    - name: Test run staged pysource (python @ ubuntu-latest)
      run: python staged/o/fused/__init__.py

  linux:
    needs: stage
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: 'pip' # caching pip dependencies

    - uses: actions/download-artifact@master
      with:
        name: fused
        path: staged/fused

    - run: python staged/bprep.py -path 'staged/fused/__init__.py' -target linux -arch x86_64 -flags '{"onefile":true,"runner":"ubuntu-latest"}'

    - uses: sayyid5416/pyinstaller@v1
      with:
        python_ver: '3.12'
        pyinstaller_ver: '==6.10.0'
        spec: 'staged/fused/__init__.py'
        requirements: 'src/requirements.txt'
        clean_checkout: false
        exe_path: "./builds"
        options: --onefile, --name "ExampleApp"

    - name: Test run built binary (linux_x86_64 @ ubuntu-latest)
      run: ./builds/ExampleApp

  windows:
    needs: stage
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: 'pip' # caching pip dependencies

    - uses: actions/download-artifact@master
      with:
        name: fused
        path: staged/fused
    
    - run: python staged/bprep.py -path 'staged/fused/__init__.py' -target windows -arch x86_64 -flags '{"onefile":true,"runner":"windows-2019"}'

    - uses: sayyid5416/pyinstaller@v1
      with:
        python_ver: '3.12'
        pyinstaller_ver: '==6.10.0'
        spec: 'staged/fused/__init__.py'
        requirements: 'src/requirements.txt'
        clean_checkout: false
        exe_path: "./builds"
        options: --onefile, --name "ExampleApp"

    - name: Test run built binary (windows_x86_64 @ windows-2019)
      run: ./builds/ExampleApp.exe

  macos:
    needs: stage
    strategy:
      matrix:
        os-version: ['12', '14']
        include:
          - os-version: '12'
            arch: x86_64
          - os-version: '14'
            arch: aarch64
    runs-on: macos-${{ matrix.os-version }}
    env:
      # even though we run on 12, target towards compatibility
      MACOSX_DEPLOYMENT_TARGET: '11.0'
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: 'pip' # caching pip dependencies

    - uses: actions/download-artifact@master
      with:
        name: fused
        path: staged/fused
    
    - run: python staged/bprep.py -path 'staged/fused/__init__.py' -target macos -arch ${{ matrix.arch }} -osver ${{ matrix.os-version }} -flags '{"onefile":true,"runner":"macos-${{ matrix.os-version }}"}'
        
    - uses: sayyid5416/pyinstaller@v1
      with:
        python_ver: '3.12'
        pyinstaller_ver: '==6.10.0'
        spec: 'staged/fused/__init__.py'
        requirements: 'src/requirements.txt'
        clean_checkout: false
        exe_path: "./builds"
        options: --onefile, --name "ExampleApp"

    - name: Test run built binary (MacOS_${{ matrix.arch }} @ MacOS-${{ matrix.os-version }})
      run: ./builds/ExampleApp


  cleanup:
    needs: [linux,windows,macos]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: geekyeggo/delete-artifact@v5
      with:
          name: fused
          failOnError: false